name: Automated Preprocessing Workflow

# Trigger: Jalan setiap kali ada push ke branch main
on:
  push:
    branches:
      - main
  workflow_dispatch: # Agar bisa di-run manual tombolnya

permissions:
  contents: write

jobs:
  preprocess-data:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil kode dari repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Siapkan Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install library yang dibutuhkan
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan script automate (dijalankan dari root folder)
    - name: Run Preprocessing Script
      run: python preprocessing/automate_M-Rafli-Kamal.py

    # 5. Cek apakah ada perubahan data, lalu Commit dan Push
    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Tambahkan file hasil preprocessing
        git add preprocessing/loan_data_cleaned_automated.csv
        
        # Commit jika ada perubahan
        git commit -m "Auto-update: Dataset preprocessing result" || echo "No changes to commit"
        
        # Push kembali ke repository
        git push